name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # roda todos os dias à meia-noite UTC
  workflow_dispatch:     # permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate snake animation
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: dingosin
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push the snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
